import React from 'react';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white text-gray-800 font-sans p-8 max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
      <p className="text-gray-500 mb-6">Last updated: February 12, 2026</p>

      <p className="mb-4">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
      <p className="mb-8">We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
      <h3 className="text-xl font-semibold mt-6 mb-2">Interpretation</h3>
      <p className="mb-4">The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

      <h3 className="text-xl font-semibold mt-6 mb-2">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc pl-6 space-y-3 mb-6">
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to pomodex.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Country</strong> refers to: New South Wales, Australia</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
        <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Website</strong> refers to pomodex, accessible from <a href="https://pomodex-gamma.vercel.app/" className="text-blue-600 underline" target="_blank" rel="noopener noreferrer">https://pomodex-gamma.vercel.app/</a>.</li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Collecting and Using Your Personal Data</h2>
      <h3 className="text-xl font-semibold mt-6 mb-2">Types of Data Collected</h3>
      <h4 className="text-lg font-semibold mt-4 mb-2">Personal Data</h4>
      <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
      <ul className="list-disc pl-6 mb-4">
        <li>First name and last name</li>
      </ul>

      <h4 className="text-lg font-semibold mt-4 mb-2">Usage Data</h4>
      <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
      <p className="mb-4">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
      <p className="mb-4">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
      <p className="mb-4">We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>

      <h4 className="text-lg font-semibold mt-4 mb-2">Tracking Technologies and Cookies</h4>
      <p className="mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:</p>
      <ul className="list-disc pl-6 space-y-3 mb-4">
        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.</li>
      </ul>
      <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
      <ul className="list-disc pl-6 space-y-3 mb-6">
        <li><strong>Necessary / Essential Cookies</strong> — Type: Session Cookies. Purpose: These Cookies are essential to provide You with services available through the Website and to authenticate users.</li>
        <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> — Type: Persistent Cookies. Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
        <li><strong>Functionality Cookies</strong> — Type: Persistent Cookies. Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details.</li>
      </ul>

      <h3 className="text-xl font-semibold mt-6 mb-2">Use of Your Personal Data</h3>
      <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
      <ul className="list-disc pl-6 space-y-3 mb-6">
        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
        <li><strong>To contact You</strong> regarding updates or informative communications related to the Service.</li>
        <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
        <li><strong>For other purposes</strong>: such as data analysis, identifying usage trends, and to evaluate and improve our Service.</li>
      </ul>

      <h3 className="text-xl font-semibold mt-6 mb-2">Retention of Your Personal Data</h3>
      <p className="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>

      <h3 className="text-xl font-semibold mt-6 mb-2">Transfer of Your Personal Data</h3>
      <p className="mb-4">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.</p>

      <h3 className="text-xl font-semibold mt-6 mb-2">Delete Your Personal Data</h3>
      <p className="mb-4">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>

      <h3 className="text-xl font-semibold mt-6 mb-2">Disclosure of Your Personal Data</h3>
      <h4 className="text-lg font-semibold mt-4 mb-2">Law enforcement</h4>
      <p className="mb-4">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>

      <h4 className="text-lg font-semibold mt-4 mb-2">Other legal requirements</h4>
      <p className="mb-2">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
      <ul className="list-disc pl-6 mb-6">
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ul>

      <h3 className="text-xl font-semibold mt-6 mb-2">Security of Your Personal Data</h3>
      <p className="mb-6">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Children's Privacy</h2>
      <p className="mb-6">Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Links to Other Websites</h2>
      <p className="mb-6">Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Changes to this Privacy Policy</h2>
      <p className="mb-6">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.</p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
      <p className="mb-2">If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul className="list-disc pl-6 mb-8">
        <li>By email: <a href="mailto:frank.imagination@gmail.com" className="text-blue-600 underline">frank.imagination@gmail.com</a></li>
      </ul>

      <a href="/" className="text-blue-600 hover:underline">← Back to app</a>
    </div>
  );
}
